/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApplicantDetail {
  'application' : Application,
  'seeker' : JobSeeker,
}
export interface Application {
  'id' : bigint,
  'status' : ApplicationStatus,
  'appliedAt' : Timestamp,
  'jobId' : bigint,
  'seekerId' : UserId,
}
export type ApplicationStatus = { 'Viewed' : null } |
  { 'Rejected' : null } |
  { 'Accepted' : null } |
  { 'Pending' : null };
export interface ApplicationWithJob { 'job' : Job, 'application' : Application }
export type Category = { 'IT' : null } |
  { 'Healthcare' : null } |
  { 'Sales' : null } |
  { 'Engineering' : null } |
  { 'Design' : null } |
  { 'Other' : null } |
  { 'Marketing' : null } |
  { 'Education' : null } |
  { 'Finance' : null };
export interface Employer {
  'id' : UserId,
  'createdAt' : Timestamp,
  'email' : string,
  'companyName' : string,
  'companyDescription' : string,
}
export interface Job {
  'id' : bigint,
  'title' : string,
  'postedAt' : Timestamp,
  'jobType' : JobType,
  'description' : string,
  'isActive' : boolean,
  'employerId' : UserId,
  'companyName' : string,
  'category' : Category,
  'salaryMax' : bigint,
  'salaryMin' : bigint,
  'requirements' : string,
  'location' : string,
}
export interface JobSeeker {
  'id' : UserId,
  'experienceLevel' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'education' : string,
  'email' : string,
  'skills' : string,
}
export type JobType = { 'PartTime' : null } |
  { 'Remote' : null } |
  { 'FullTime' : null };
export type LoginResult = { 'ok' : UserRole } |
  { 'err' : string };
export type Timestamp = bigint;
export type UserId = Principal;
export type UserRole = { 'JobSeeker' : null } |
  { 'Employer' : null };
export interface _SERVICE {
  'applyForJob' : ActorMethod<
    [bigint],
    { 'ok' : Application } |
      { 'err' : string }
  >,
  'deleteJob' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'getEmployerJobs' : ActorMethod<[], Array<Job>>,
  'getEmployerProfile' : ActorMethod<[], [] | [Employer]>,
  'getFeaturedJobs' : ActorMethod<[], Array<Job>>,
  'getJob' : ActorMethod<[bigint], [] | [Job]>,
  'getJobApplicants' : ActorMethod<
    [bigint],
    { 'ok' : Array<ApplicantDetail> } |
      { 'err' : string }
  >,
  'getJobCategories' : ActorMethod<[], Array<Category>>,
  'getMyRole' : ActorMethod<[], LoginResult>,
  'getRecentJobs' : ActorMethod<[], Array<Job>>,
  'getSeekerApplications' : ActorMethod<[], Array<ApplicationWithJob>>,
  'getSeekerProfile' : ActorMethod<[], [] | [JobSeeker]>,
  'postJob' : ActorMethod<
    [string, string, string, JobType, Category, string, bigint, bigint],
    { 'ok' : Job } |
      { 'err' : string }
  >,
  'registerEmployer' : ActorMethod<
    [string, string, string],
    { 'ok' : Employer } |
      { 'err' : string }
  >,
  'registerJobSeeker' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : JobSeeker } |
      { 'err' : string }
  >,
  'searchJobs' : ActorMethod<
    [
      string,
      string,
      [] | [Category],
      [] | [JobType],
      [] | [bigint],
      [] | [bigint],
    ],
    Array<Job>
  >,
  'updateApplicationStatus' : ActorMethod<
    [bigint, ApplicationStatus],
    { 'ok' : Application } |
      { 'err' : string }
  >,
  'updateJob' : ActorMethod<
    [bigint, string, string, string, JobType, Category, string, bigint, bigint],
    { 'ok' : Job } |
      { 'err' : string }
  >,
  'updateSeekerProfile' : ActorMethod<
    [string, string, string, string],
    { 'ok' : JobSeeker } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];