/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApplicationStatus = IDL.Variant({
  'Viewed' : IDL.Null,
  'Rejected' : IDL.Null,
  'Accepted' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const Application = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'appliedAt' : Timestamp,
  'jobId' : IDL.Nat,
  'seekerId' : UserId,
});
export const JobType = IDL.Variant({
  'PartTime' : IDL.Null,
  'Remote' : IDL.Null,
  'FullTime' : IDL.Null,
});
export const Category = IDL.Variant({
  'IT' : IDL.Null,
  'Healthcare' : IDL.Null,
  'Sales' : IDL.Null,
  'Engineering' : IDL.Null,
  'Design' : IDL.Null,
  'Other' : IDL.Null,
  'Marketing' : IDL.Null,
  'Education' : IDL.Null,
  'Finance' : IDL.Null,
});
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'postedAt' : Timestamp,
  'jobType' : JobType,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'employerId' : UserId,
  'companyName' : IDL.Text,
  'category' : Category,
  'salaryMax' : IDL.Nat,
  'salaryMin' : IDL.Nat,
  'requirements' : IDL.Text,
  'location' : IDL.Text,
});
export const Employer = IDL.Record({
  'id' : UserId,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'companyName' : IDL.Text,
  'companyDescription' : IDL.Text,
});
export const JobSeeker = IDL.Record({
  'id' : UserId,
  'experienceLevel' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'education' : IDL.Text,
  'email' : IDL.Text,
  'skills' : IDL.Text,
});
export const ApplicantDetail = IDL.Record({
  'application' : Application,
  'seeker' : JobSeeker,
});
export const UserRole = IDL.Variant({
  'JobSeeker' : IDL.Null,
  'Employer' : IDL.Null,
});
export const LoginResult = IDL.Variant({ 'ok' : UserRole, 'err' : IDL.Text });
export const ApplicationWithJob = IDL.Record({
  'job' : Job,
  'application' : Application,
});

export const idlService = IDL.Service({
  'applyForJob' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
      [],
    ),
  'deleteJob' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getEmployerJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getEmployerProfile' : IDL.Func([], [IDL.Opt(Employer)], ['query']),
  'getFeaturedJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
  'getJobApplicants' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Vec(ApplicantDetail), 'err' : IDL.Text })],
      ['query'],
    ),
  'getJobCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getMyRole' : IDL.Func([], [LoginResult], ['query']),
  'getRecentJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getSeekerApplications' : IDL.Func(
      [],
      [IDL.Vec(ApplicationWithJob)],
      ['query'],
    ),
  'getSeekerProfile' : IDL.Func([], [IDL.Opt(JobSeeker)], ['query']),
  'postJob' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        JobType,
        Category,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Variant({ 'ok' : Job, 'err' : IDL.Text })],
      [],
    ),
  'registerEmployer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Employer, 'err' : IDL.Text })],
      [],
    ),
  'registerJobSeeker' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : JobSeeker, 'err' : IDL.Text })],
      [],
    ),
  'searchJobs' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(Category),
        IDL.Opt(JobType),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Vec(Job)],
      ['query'],
    ),
  'updateApplicationStatus' : IDL.Func(
      [IDL.Nat, ApplicationStatus],
      [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
      [],
    ),
  'updateJob' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        JobType,
        Category,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Variant({ 'ok' : Job, 'err' : IDL.Text })],
      [],
    ),
  'updateSeekerProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : JobSeeker, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApplicationStatus = IDL.Variant({
    'Viewed' : IDL.Null,
    'Rejected' : IDL.Null,
    'Accepted' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const Application = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'appliedAt' : Timestamp,
    'jobId' : IDL.Nat,
    'seekerId' : UserId,
  });
  const JobType = IDL.Variant({
    'PartTime' : IDL.Null,
    'Remote' : IDL.Null,
    'FullTime' : IDL.Null,
  });
  const Category = IDL.Variant({
    'IT' : IDL.Null,
    'Healthcare' : IDL.Null,
    'Sales' : IDL.Null,
    'Engineering' : IDL.Null,
    'Design' : IDL.Null,
    'Other' : IDL.Null,
    'Marketing' : IDL.Null,
    'Education' : IDL.Null,
    'Finance' : IDL.Null,
  });
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'postedAt' : Timestamp,
    'jobType' : JobType,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'employerId' : UserId,
    'companyName' : IDL.Text,
    'category' : Category,
    'salaryMax' : IDL.Nat,
    'salaryMin' : IDL.Nat,
    'requirements' : IDL.Text,
    'location' : IDL.Text,
  });
  const Employer = IDL.Record({
    'id' : UserId,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'companyName' : IDL.Text,
    'companyDescription' : IDL.Text,
  });
  const JobSeeker = IDL.Record({
    'id' : UserId,
    'experienceLevel' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'education' : IDL.Text,
    'email' : IDL.Text,
    'skills' : IDL.Text,
  });
  const ApplicantDetail = IDL.Record({
    'application' : Application,
    'seeker' : JobSeeker,
  });
  const UserRole = IDL.Variant({
    'JobSeeker' : IDL.Null,
    'Employer' : IDL.Null,
  });
  const LoginResult = IDL.Variant({ 'ok' : UserRole, 'err' : IDL.Text });
  const ApplicationWithJob = IDL.Record({
    'job' : Job,
    'application' : Application,
  });
  
  return IDL.Service({
    'applyForJob' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
        [],
      ),
    'deleteJob' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getEmployerJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getEmployerProfile' : IDL.Func([], [IDL.Opt(Employer)], ['query']),
    'getFeaturedJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
    'getJobApplicants' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Vec(ApplicantDetail), 'err' : IDL.Text })],
        ['query'],
      ),
    'getJobCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getMyRole' : IDL.Func([], [LoginResult], ['query']),
    'getRecentJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getSeekerApplications' : IDL.Func(
        [],
        [IDL.Vec(ApplicationWithJob)],
        ['query'],
      ),
    'getSeekerProfile' : IDL.Func([], [IDL.Opt(JobSeeker)], ['query']),
    'postJob' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          JobType,
          Category,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Variant({ 'ok' : Job, 'err' : IDL.Text })],
        [],
      ),
    'registerEmployer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Employer, 'err' : IDL.Text })],
        [],
      ),
    'registerJobSeeker' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : JobSeeker, 'err' : IDL.Text })],
        [],
      ),
    'searchJobs' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(Category),
          IDL.Opt(JobType),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Vec(Job)],
        ['query'],
      ),
    'updateApplicationStatus' : IDL.Func(
        [IDL.Nat, ApplicationStatus],
        [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
        [],
      ),
    'updateJob' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          JobType,
          Category,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Variant({ 'ok' : Job, 'err' : IDL.Text })],
        [],
      ),
    'updateSeekerProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : JobSeeker, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };