/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface Job {
    id: bigint;
    title: string;
    postedAt: Timestamp;
    jobType: JobType;
    description: string;
    isActive: boolean;
    employerId: UserId;
    companyName: string;
    category: Category;
    salaryMax: bigint;
    salaryMin: bigint;
    requirements: string;
    location: string;
}
export interface Application {
    id: bigint;
    status: ApplicationStatus;
    appliedAt: Timestamp;
    jobId: bigint;
    seekerId: UserId;
}
export interface ApplicantDetail {
    application: Application;
    seeker: JobSeeker;
}
export interface Employer {
    id: UserId;
    createdAt: Timestamp;
    email: string;
    companyName: string;
    companyDescription: string;
}
export type LoginResult = {
    __kind__: "ok";
    ok: UserRole;
} | {
    __kind__: "err";
    err: string;
};
export interface ApplicationWithJob {
    job: Job;
    application: Application;
}
export interface JobSeeker {
    id: UserId;
    experienceLevel: string;
    name: string;
    createdAt: Timestamp;
    education: string;
    email: string;
    skills: string;
}
export enum ApplicationStatus {
    Viewed = "Viewed",
    Rejected = "Rejected",
    Accepted = "Accepted",
    Pending = "Pending"
}
export enum Category {
    IT = "IT",
    Healthcare = "Healthcare",
    Sales = "Sales",
    Engineering = "Engineering",
    Design = "Design",
    Other = "Other",
    Marketing = "Marketing",
    Education = "Education",
    Finance = "Finance"
}
export enum JobType {
    PartTime = "PartTime",
    Remote = "Remote",
    FullTime = "FullTime"
}
export enum UserRole {
    JobSeeker = "JobSeeker",
    Employer = "Employer"
}
export interface backendInterface {
    applyForJob(jobId: bigint): Promise<{
        __kind__: "ok";
        ok: Application;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteJob(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getEmployerJobs(): Promise<Array<Job>>;
    getEmployerProfile(): Promise<Employer | null>;
    getFeaturedJobs(): Promise<Array<Job>>;
    getJob(id: bigint): Promise<Job | null>;
    getJobApplicants(jobId: bigint): Promise<{
        __kind__: "ok";
        ok: Array<ApplicantDetail>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getJobCategories(): Promise<Array<Category>>;
    getMyRole(): Promise<LoginResult>;
    getRecentJobs(): Promise<Array<Job>>;
    getSeekerApplications(): Promise<Array<ApplicationWithJob>>;
    getSeekerProfile(): Promise<JobSeeker | null>;
    postJob(title: string, description: string, requirements: string, jobType: JobType, category: Category, location: string, salaryMin: bigint, salaryMax: bigint): Promise<{
        __kind__: "ok";
        ok: Job;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerEmployer(email: string, companyName: string, companyDescription: string): Promise<{
        __kind__: "ok";
        ok: Employer;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerJobSeeker(email: string, name: string, skills: string, experienceLevel: string, education: string): Promise<{
        __kind__: "ok";
        ok: JobSeeker;
    } | {
        __kind__: "err";
        err: string;
    }>;
    searchJobs(keyword: string, location: string, category: Category | null, jobType: JobType | null, salaryMin: bigint | null, salaryMax: bigint | null): Promise<Array<Job>>;
    updateApplicationStatus(appId: bigint, status: ApplicationStatus): Promise<{
        __kind__: "ok";
        ok: Application;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateJob(id: bigint, title: string, description: string, requirements: string, jobType: JobType, category: Category, location: string, salaryMin: bigint, salaryMax: bigint): Promise<{
        __kind__: "ok";
        ok: Job;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateSeekerProfile(name: string, skills: string, experienceLevel: string, education: string): Promise<{
        __kind__: "ok";
        ok: JobSeeker;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { ApplicantDetail as _ApplicantDetail, Application as _Application, ApplicationStatus as _ApplicationStatus, ApplicationWithJob as _ApplicationWithJob, Category as _Category, Employer as _Employer, Job as _Job, JobSeeker as _JobSeeker, JobType as _JobType, LoginResult as _LoginResult, Timestamp as _Timestamp, UserId as _UserId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async applyForJob(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: Application;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.applyForJob(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyForJob(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteJob(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployerJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployerJobs();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployerJobs();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployerProfile(): Promise<Employer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployerProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployerProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedJobs();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedJobs();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJob(arg0: bigint): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobApplicants(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: Array<ApplicantDetail>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobApplicants(arg0);
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobApplicants(arg0);
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobCategories();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobCategories();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRole(): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole();
                return from_candid_LoginResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole();
            return from_candid_LoginResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentJobs();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentJobs();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSeekerApplications(): Promise<Array<ApplicationWithJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSeekerApplications();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSeekerApplications();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSeekerProfile(): Promise<JobSeeker | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSeekerProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSeekerProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async postJob(arg0: string, arg1: string, arg2: string, arg3: JobType, arg4: Category, arg5: string, arg6: bigint, arg7: bigint): Promise<{
        __kind__: "ok";
        ok: Job;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.postJob(arg0, arg1, arg2, to_candid_JobType_n29(this._uploadFile, this._downloadFile, arg3), to_candid_Category_n31(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7);
                return from_candid_variant_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postJob(arg0, arg1, arg2, to_candid_JobType_n29(this._uploadFile, this._downloadFile, arg3), to_candid_Category_n31(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7);
            return from_candid_variant_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerEmployer(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: Employer;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerEmployer(arg0, arg1, arg2);
                return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerEmployer(arg0, arg1, arg2);
            return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerJobSeeker(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<{
        __kind__: "ok";
        ok: JobSeeker;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerJobSeeker(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerJobSeeker(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchJobs(arg0: string, arg1: string, arg2: Category | null, arg3: JobType | null, arg4: bigint | null, arg5: bigint | null): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchJobs(arg0, arg1, to_candid_opt_n36(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n37(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n38(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n38(this._uploadFile, this._downloadFile, arg5));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchJobs(arg0, arg1, to_candid_opt_n36(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n37(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n38(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n38(this._uploadFile, this._downloadFile, arg5));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateApplicationStatus(arg0: bigint, arg1: ApplicationStatus): Promise<{
        __kind__: "ok";
        ok: Application;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n39(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n39(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateJob(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: JobType, arg5: Category, arg6: string, arg7: bigint, arg8: bigint): Promise<{
        __kind__: "ok";
        ok: Job;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(arg0, arg1, arg2, arg3, to_candid_JobType_n29(this._uploadFile, this._downloadFile, arg4), to_candid_Category_n31(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8);
                return from_candid_variant_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(arg0, arg1, arg2, arg3, to_candid_JobType_n29(this._uploadFile, this._downloadFile, arg4), to_candid_Category_n31(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8);
            return from_candid_variant_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSeekerProfile(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: JobSeeker;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSeekerProfile(arg0, arg1, arg2, arg3);
                return from_candid_variant_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSeekerProfile(arg0, arg1, arg2, arg3);
            return from_candid_variant_n35(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ApplicantDetail_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicantDetail): ApplicantDetail {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ApplicationStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ApplicationWithJob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationWithJob): ApplicationWithJob {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Application_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Application): Application {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_JobType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobType): JobType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_LoginResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Employer]): Employer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : from_candid_Job_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobSeeker]): JobSeeker | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    application: _Application;
    seeker: _JobSeeker;
}): {
    application: Application;
    seeker: JobSeeker;
} {
    return {
        application: from_candid_Application_n2(_uploadFile, _downloadFile, value.application),
        seeker: value.seeker
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    job: _Job;
    application: _Application;
}): {
    job: Job;
    application: Application;
} {
    return {
        job: from_candid_Job_n8(_uploadFile, _downloadFile, value.job),
        application: from_candid_Application_n2(_uploadFile, _downloadFile, value.application)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ApplicationStatus;
    appliedAt: _Timestamp;
    jobId: bigint;
    seekerId: _UserId;
}): {
    id: bigint;
    status: ApplicationStatus;
    appliedAt: Timestamp;
    jobId: bigint;
    seekerId: UserId;
} {
    return {
        id: value.id,
        status: from_candid_ApplicationStatus_n4(_uploadFile, _downloadFile, value.status),
        appliedAt: value.appliedAt,
        jobId: value.jobId,
        seekerId: value.seekerId
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    postedAt: _Timestamp;
    jobType: _JobType;
    description: string;
    isActive: boolean;
    employerId: _UserId;
    companyName: string;
    category: _Category;
    salaryMax: bigint;
    salaryMin: bigint;
    requirements: string;
    location: string;
}): {
    id: bigint;
    title: string;
    postedAt: Timestamp;
    jobType: JobType;
    description: string;
    isActive: boolean;
    employerId: UserId;
    companyName: string;
    category: Category;
    salaryMax: bigint;
    salaryMin: bigint;
    requirements: string;
    location: string;
} {
    return {
        id: value.id,
        title: value.title,
        postedAt: value.postedAt,
        jobType: from_candid_JobType_n10(_uploadFile, _downloadFile, value.jobType),
        description: value.description,
        isActive: value.isActive,
        employerId: value.employerId,
        companyName: value.companyName,
        category: from_candid_Category_n12(_uploadFile, _downloadFile, value.category),
        salaryMax: value.salaryMax,
        salaryMin: value.salaryMin,
        requirements: value.requirements,
        location: value.location
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Application;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Application;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Application_n2(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    PartTime: null;
} | {
    Remote: null;
} | {
    FullTime: null;
}): JobType {
    return "PartTime" in value ? JobType.PartTime : "Remote" in value ? JobType.Remote : "FullTime" in value ? JobType.FullTime : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    IT: null;
} | {
    Healthcare: null;
} | {
    Sales: null;
} | {
    Engineering: null;
} | {
    Design: null;
} | {
    Other: null;
} | {
    Marketing: null;
} | {
    Education: null;
} | {
    Finance: null;
}): Category {
    return "IT" in value ? Category.IT : "Healthcare" in value ? Category.Healthcare : "Sales" in value ? Category.Sales : "Engineering" in value ? Category.Engineering : "Design" in value ? Category.Design : "Other" in value ? Category.Other : "Marketing" in value ? Category.Marketing : "Education" in value ? Category.Education : "Finance" in value ? Category.Finance : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_ApplicantDetail>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<ApplicantDetail>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n17(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserRole;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserRole;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserRole_n23(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    JobSeeker: null;
} | {
    Employer: null;
}): UserRole {
    return "JobSeeker" in value ? UserRole.JobSeeker : "Employer" in value ? UserRole.Employer : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Job;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Job;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Job_n8(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Employer;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Employer;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _JobSeeker;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: JobSeeker;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Viewed: null;
} | {
    Rejected: null;
} | {
    Accepted: null;
} | {
    Pending: null;
}): ApplicationStatus {
    return "Viewed" in value ? ApplicationStatus.Viewed : "Rejected" in value ? ApplicationStatus.Rejected : "Accepted" in value ? ApplicationStatus.Accepted : "Pending" in value ? ApplicationStatus.Pending : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApplicantDetail>): Array<ApplicantDetail> {
    return value.map((x)=>from_candid_ApplicantDetail_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Category>): Array<Category> {
    return value.map((x)=>from_candid_Category_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApplicationWithJob>): Array<ApplicationWithJob> {
    return value.map((x)=>from_candid_ApplicationWithJob_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n8(_uploadFile, _downloadFile, x));
}
function to_candid_ApplicationStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): _ApplicationStatus {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_JobType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): _JobType {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category | null): [] | [_Category] {
    return value === null ? candid_none() : candid_some(to_candid_Category_n31(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType | null): [] | [_JobType] {
    return value === null ? candid_none() : candid_some(to_candid_JobType_n29(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): {
    PartTime: null;
} | {
    Remote: null;
} | {
    FullTime: null;
} {
    return value == JobType.PartTime ? {
        PartTime: null
    } : value == JobType.Remote ? {
        Remote: null
    } : value == JobType.FullTime ? {
        FullTime: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    IT: null;
} | {
    Healthcare: null;
} | {
    Sales: null;
} | {
    Engineering: null;
} | {
    Design: null;
} | {
    Other: null;
} | {
    Marketing: null;
} | {
    Education: null;
} | {
    Finance: null;
} {
    return value == Category.IT ? {
        IT: null
    } : value == Category.Healthcare ? {
        Healthcare: null
    } : value == Category.Sales ? {
        Sales: null
    } : value == Category.Engineering ? {
        Engineering: null
    } : value == Category.Design ? {
        Design: null
    } : value == Category.Other ? {
        Other: null
    } : value == Category.Marketing ? {
        Marketing: null
    } : value == Category.Education ? {
        Education: null
    } : value == Category.Finance ? {
        Finance: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): {
    Viewed: null;
} | {
    Rejected: null;
} | {
    Accepted: null;
} | {
    Pending: null;
} {
    return value == ApplicationStatus.Viewed ? {
        Viewed: null
    } : value == ApplicationStatus.Rejected ? {
        Rejected: null
    } : value == ApplicationStatus.Accepted ? {
        Accepted: null
    } : value == ApplicationStatus.Pending ? {
        Pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
